version: '3.4'

services:

  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy/Caddyfile:/etc/Caddyfile

  postgres:
    image: postgres:11-beta2-alpine
    environment:      
      - POSTGRES_PASSWORD=temporary   
    ports:
      - "5432:5432"   
    volumes:
      - postgresql:/var/lib/postgresql/data    

  pgadmin:
    image: dpage/pgadmin4  
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=temporary
    ports:
      - "81:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  postgrest:
    image: postgrest/postgrest
    ports:
      - "82:3000"
    environment:
      PGRST_DB_URI: postgresql://postgres:temporary@postgres:5432/cvmData
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres # In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: http://localhost:82/
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "83:8080"
    environment:
      API_URL: http://127.0.0.1:82/

  docker-container-crontab:
    image: conradoqg/cvm-fund-explorer-docker-container-crontab:latest    

volumes:
  postgresql:
    external: true