version: '3.4'

services:

  caddy:
    image: abiosoft/caddy:latest
    ports:
      - 80:80
      - 443:443    

  postgres:
    image: postgres:11-beta2-alpine    
    volumes:
      - postgresql:/var/lib/postgresql/data        

  pgadmin:
    image: dpage/pgadmin4:latest    
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  postgrest:
    image: postgrest/postgrest:latest        
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui:latest    
    environment:
      - PORT=80
      - API_URL=/
      - BASE_URL=/doc

  docker-container-crontab:
    image: conradoqg/cvm-fund-explorer-docker-container-crontab:latest    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ '-d' ]

volumes:
  postgresql:
    external: true
  pgadmin:
    external: true