# kubetpl:syntax:$

apiVersion: v1
kind: Service
metadata:
  namespace: meajudafi
  name: swagger-service
  labels:
    app: swagger
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http 
  selector:
    app: swagger
  type: LoadBalancer