# kubetpl:syntax:$

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: meajudafi
  name: worker-all-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi